### ISSUE TITLE
Remove 3rd party libs and install via bower?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-easter-egg#1]
Instead of bundling mocha/chai/sinon, should we just install via bower?

**Comment by TDA** [comment]
@pdehaan Mocha, Chai and Sinon are only for tests inside this repo, only the easterEgg.js file is actually used in the content-server. I could completely remove the tests, seeing as they arent really required.

**Comment by pdehaan** [comment]
By the powers of force push and single commit repos, I dare say this was completed as I now see a bower.json file with some dependencies and such).

Closing.

**Comment by TDA** [comment]
@pdehaan I laughed way harder than I should have.

**Comment by pdehaan** [comment]
When we say "squash commits" we don't mean that this repo has to have only a single commit. Feel free to ease off that `--amend` flag.

**Comment by TDA** [comment]
Eased off General. Eased off.
