### ISSUE TITLE
localStorage data management suggestion - don't store the strings 'true' & 'false'

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-easter-egg#12]
Instead of storing both 'true' and 'false', if the user disables the easter egg, I would store 'false', and then if the user re-enables the easter egg, remove the namespace from localStorage entirely.

Ref https://github.com/mozilla/fxa-easter-egg/blob/47f63d70d2159b14465e305c3562d0b63f1513c0/src/easteregg.js#L11

**Comment by vladikoff** [comment]
inactive issue, reopen if we are still planning to make changes to this
