### ISSUE TITLE
Add a couple of newlines to beginning of console.log() message

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-easter-egg#5]
Just to protect ourselves from potential logging issues between Chrome/Safari/Firefox, as some may precede the `console.log()` statements with timestamps or whatever.

Ref: [/easterEgg.js:48](https://github.com/mozilla/fxa-easter-egg/blob/7d50f32c056e9658c485c651577d4e1d16bb5b66/easterEgg.js#L48)

**Comment by TDA** [comment]
done! @pdehaan
