### ISSUE TITLE
Audit bower.json

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-easter-egg#6]
Re: https://github.com/mozilla/fxa-easter-egg/blob/master/bower.json

Currently I have a few suspicions about our existing bower.json before we try publishing a version to Bower registry:
1. Change `name` to something more specific, like maybe `fxa-easter-egg`. So we'd install like `bower install fxa-easter-egg -S` versus the genericly named `bower install easterEgg`.
2. Is `main` right? Or should that be `src/easterEgg.js`?
3. Should we rename `src/easterEgg.js` to `src/easteregg.js` or `src/easter-egg.js`?
4. Change `description` to mention Mozilla maybe?
   
   > "Console easter egg for Mozilla Firefox Accounts."
   
   or possibly:
   
   > "Console easter egg for Mozilla Cloud Services."
5. Is `license` correct here, or do we want to use `"MPL-2.0"`?

/cc @shane-tomlinson Since I don't know the answers to any of the above.

**Comment by TDA** [comment]
@pdehaan Fixed. Closing!
